version: "3"

services:
        postgres:
                image: postgres
                environment: 
                        - POSTGRES_USER=test
                        - POSTGRES_PASSWORD=test
                        - POSTGRES_DB=test
                ports:
                        - "8000:5432"
        migrate:
                image: migrate/migrate
                volumes:
                        - ./database:/migrations
                command: ["-path", "/migrations", "-database", "postgres://test:test@postgres:5432/test?sslmode=disable", "up"]
                restart: on-failure

